# Generated by Django 3.1 on 2021-11-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_size',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
